version: "3"
services:
    hub:
        image: selenium/hub
    chrome:
        image: selenium/node-chrome
        shm_size: '1gb' 
        depends_on:
            - hub
        environment:
            - HUB_HOST=hub
    firefox:
        image: selenium/node-firefox
        shm_size: '1gb' 
        depends_on:
            - hub
        environment:
            - HUB_HOST=hub
    search-module1:
        image: mogreat1/selenium-docker
        depends_on:
            - chrome
            - firefox
        environment:
            - BROWSER=chrome
            - HUB_HOST=hub
            - MODULE=search-module.xml
        volumes:
            - ./search-result1:/user/share/test/test-output
    search-module2:
        image: mogreat1/selenium-docker
        depends_on:
            - chrome
            - firefox
        environment:
            - BROWSER=firefox
            - HUB_HOST=hub
            - MODULE=search-module.xml
        volumes:
            - ./search-result2:/user/share/test/test-output
    book-flight-module1:
        image: mogreat1/selenium-docker
        depends_on:
          - chrome
          - firefox
        environment:
            - BROWSER=chrome
            - HUB_HOST=hub
            - MODULE=book-flight-module.xml
        volumes:
            - ./book-result1:/user/share/test/test-output
    book-flight-module2:
        image: mogreat1/selenium-docker
        depends_on:
            - chrome
            - firefox
        environment:
            - BROWSER=chrome
            - HUB_HOST=hub
            - MODULE=book-flight-module.xml
        volumes:
            - ./book-result2:/user/share/test/test-output